#!/bin/sh
# This function runs the feature extraction binary for the generated
# stereo pairs (see make_train_stereo_pairs.sh). This function uses a
# test image list file similar to automatically generated by make_test_stereo_pairs.sh:
#
#  <stereo_left_img> <stereo_right_img> <camera_left_dat> <camera_right_dat> <basename> <classname>
#
# <basename> will be used to name the output files
# Usage: prompt:~>source make_train_stereo_pairs.sh <train_obj_file> [<output_dir>]

tempwork_dir="TEMPWORK"
slam_config_skeleton="data/KIT_slam_config_skeleton_for_testset.xml";
slam_bin="./slam";

printf "=> Using Slam config skeleton: $slam_config_skeleton \n";

if [ $# -eq 0 ]; then
    echo "Not enough input arguments!";
    echo "Usage: source extract_test_primitives.sh <test_list_file> [<tempwork_dir>]";
    echo " Example: source scripts/extract_test_primitives.sh kit-lut_EAZ_40_nozoom_test_set.txt";
    return 1;
fi;

if [ $# -eq 1 ]; then
    tempwork_dir=${tempwork_dir%/}; # removes last slash if exists
    echo "=> Using default temporary work directory " $tempwork_dir;
fi;

if [ $# -eq 2 ]; then
    tempwork_dir=${2%/}; # removes last slash if exists
    echo $tempwork_dir;
fi;


while read -r lline
do
    if [[ ! "$lline" == "#"* ]]; then # Skip comment lines
	line_ar=( $lline );
	basename=${line_ar[3]};
	echo $basename
	mkdir -p "${tempwork_dir}/Slam_output_${basename}";
	sed -e "s/@BASENAME@/$basename/g" \
	    -e "s/@BASEDIR@/$tempwork_dir/g" \
	    -e "s/@STEREOLEFT@/${line_ar[0]}/g" \
	    -e "s/@STEREORIGHT@/${line_ar[1]}/g" \
	    -e "s/@CAMERA@/${line_ar[2]}/g" \
	    $slam_config_skeleton > "${tempwork_dir}/Slam_config_${basename}_test.xml";
	$slam_bin --images "${tempwork_dir}/Slam_config_${basename}_test.xml" > /dev/null;
    fi
done < $1

